# use to extract patterns
ASCENDING = "ASCENDING"
DESCENDING = "DESCENDING"
# trigger directions
ABOVE = "ABOVE"
BELOW = "BELOW"
BETWEEN = "BETWEEN"

#stochastic oscillator
STOCH_SUB_RSI = "RSI"
TRIGGER_CAUSE_SLOW_MA = "SLOW_MA"
TRIGGER_CAUSE_FAST_MA = "FAST_MA"
TRIGGER_CAUSE_FAST_AND_SLOW_MA = "FAST_AND_SLOW_MA"